export const CoursesData = [
  {
    id: 1,
    category: "Design",
    title: "Introduction to user research in UX Design",
    imageSrc: "src/assets/images/courseImage1.png",
    rating: "4.7",
    studentCount: "32.7k+",
    duration: "23hrs 50mins",
    lessonCount: "15",
    instructorName: "Leonard Victor",
    instructorIcon: "src/assets/images/LeoVictorIcon.png",
    instructorProfession: "Product Design",
    price: 15,
    note: "high-defination video is video of higher resolution and quality than standard definition. high-defination video is video of higher resolution and quality than standard definition. hbuild your future with our quality education. the best and largest all-in-one online tutoring platform in the worldd definition. high-defination video is video of higher resolution and quality than standard definition. build your future with our quality education. the best and largest all-in-one online tutoring platform in the world",
  },
  {
    id: 2,
    category: "Marketing",
    title: "Introduction to new marketing audience",
    imageSrc: "src/assets/images/courseImage2.png",
    rating: "4.7",
    studentCount: "8.7k+",
    duration: "22hrs 30mins",
    lessonCount: "22",
    instructorName: "Jeffery Williams",
    instructorIcon: "src/assets/images/JeffWilliamsIcon.png",
    instructorProfession: "Tech Sales",
    price: 32,
    note: "high-defination video is video of higher resolution and quality than standard definition. high-defination video is video of higher resolution and quality than standard definition. hbuild your future with our quality education. the best and largest all-in-one online tutoring platform in the worldd definition. high-defination video is video of higher resolution and quality than standard definition. build your future with our quality education. the best and largest all-in-one online tutoring platform in the world",
  },
  {
    id: 3,
    category: "Development",
    title: "Introduction to HTML, CSS & Bootstrap",
    imageSrc: "src/assets/images/courseImage3.png",
    rating: "4.7",
    studentCount: "12.7k+",
    duration: "45hrs 50mins",
    lessonCount: "55",
    instructorName: "Claretta Mason",
    instructorIcon: "src/assets/images/ClaretMasonIcon.png",
    instructorProfession: "Software Engineer",
    price: 55,
    note: "high-defination video is video of higher resolution and quality than standard definition. high-defination video is video of higher resolution and quality than standard definition. hbuild your future with our quality education. the best and largest all-in-one online tutoring platform in the worldd definition. high-defination video is video of higher resolution and quality than standard definition. build your future with our quality education. the best and largest all-in-one online tutoring platform in the world",
  },
  {
    id: 4,
    category: "Development",
    title: "Introduction to JavaScript, Git and Github",
    imageSrc: "src/assets/images/courseImage4.png",
    rating: "4.7",
    studentCount: "32.7k+",
    duration: "30hrs 50mins",
    lessonCount: "22",
    instructorName: "Jessica Duke",
    instructorIcon: "src/assets/images/JessicaDukeIcon.png",
    instructorProfession: "Software Engineer",
    price: 45,
    note: "high-defination video is video of higher resolution and quality than standard definition. high-defination video is video of higher resolution and quality than standard definition. hbuild your future with our quality education. the best and largest all-in-one online tutoring platform in the worldd definition. high-defination video is video of higher resolution and quality than standard definition. build your future with our quality education. the best and largest all-in-one online tutoring platform in the world",
  },
  {
    id: 5,
    category: "Marketing",
    title: "Introduction to outroom market analysis",
    imageSrc: "src/assets/images/courseImage5.png",
    rating: "4.7",
    studentCount: "4.7k+",
    duration: "43hrs 50mins",
    lessonCount: "26",
    instructorName: "Samuel Jacobs",
    instructorIcon: "src/assets/images/SamJacobsIcon.png",
    instructorProfession: "Tech Sales",
    price: 25,
    note: "high-defination video is video of higher resolution and quality than standard definition. high-defination video is video of higher resolution and quality than standard definition. hbuild your future with our quality education. the best and largest all-in-one online tutoring platform in the worldd definition. high-defination video is video of higher resolution and quality than standard definition. build your future with our quality education. the best and largest all-in-one online tutoring platform in the world",
  },
  {
    id: 6,
    category: "Marketing",
    title: "Introduction to live marketing analysis",
    imageSrc: "src/assets/images/courseImage6.png",
    rating: "4.7",
    studentCount: "15.7k+",
    duration: "3hrs 50mins",
    lessonCount: "32",
    instructorName: "Adam Smith",
    instructorIcon: "src/assets/images/AdamSmithIcon.png",
    instructorProfession: "Tech Sales",
    price: 25,
    note: "high-defination video is video of higher resolution and quality than standard definition. high-defination video is video of higher resolution and quality than standard definition. hbuild your future with our quality education. the best and largest all-in-one online tutoring platform in the worldd definition. high-defination video is video of higher resolution and quality than standard definition. build your future with our quality education. the best and largest all-in-one online tutoring platform in the world",
  },
];
